import Layout from '@/components/Layout';
import Head from 'next/head';
import { Canvas } from '@react-three/fiber';
import { Text, OrbitControls } from '@react-three/drei';
import Link from 'next/link';
import Typewriter from 'typewriter-effect';
import { LinkArrow } from '@/components/Icons';

const languages = ["Python", "Java", "C#", "JavaScript", "C++", "Ruby", "Go", "TypeScript", "PHP", "Swift"];

const SphereWithText = () => {
  return (
    <group>
      {languages.map((lang, index) => (
        <Text
          key={lang}
          color="black"
          fontSize={0.1}
          position={[Math.sin((index / languages.length) * Math.PI * 2) * 1.2, Math.cos((index / languages.length) * Math.PI * 2) * 1.2, 0]}
          rotation={[0, 0, (index / languages.length) * Math.PI * 2]}>
          {lang}
        </Text>
      ))}
      <mesh>
        <sphereGeometry args={[1, 32, 32]} />
        <meshStandardMaterial color="lightblue" wireframe />
      </mesh>
    </group>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Kenneth Camacho</title>
        <meta name="description" content="Generated by Kenneth Camacho" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Canvas>
                <OrbitControls />
                <ambientLight intensity={0.5} />
                <pointLight position={[10, 10, 10]} />
                <SphereWithText />
              </Canvas>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center text-5xl font-semibold">
              <h1>
                  <Typewriter
                      options={{
                          strings: [
                              ' Welcome to my Portfolio!',
                              'Discover Innovative Solutions',
                              'Explore My Projects & Achievements',
                              'Journey with Me in Technology'
                          ],
                          autoStart: true,
                          loop: true,
                      }}
                  />
              </h1>
              <p className='my-4 text-base font-medium md:text-md sm:text-sm' style={{ textIndent: '50px' }}>
                I'm Kenneth Camacho, a software engineering student at Florida State University with a knack for developing innovative solutions. In this portfolio, you'll find a showcase of my projects ranging from AI-driven applications to full-stack development. Each project reflects my commitment to quality, efficiency, and user-centric design. Dive in to see how my work at Sebanda Insurance, as a Team Lead at Founders Deep Learning Startup, and various freelance endeavors have shaped my professional journey. I'm excited to share these experiences with you.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/Kenneth_Camacho_Resume.pdf" target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light md:p-2 md:px-4 md:text-base'>
                  Resume 
                </Link>
                <a href="mailto:kennethcxv@outlook.com" target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">
                  Contact
                </a>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
